CREATE TABLE IF NOT EXISTS person(
    id BIGINT(19) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    document VARCHAR(14) NOT NULL,
    contact VARCHAR(15) NULL,
    email VARCHAR(255) NULL
);
