CREATE TABLE IF NOT EXISTS Person(
    id BIGINT(19) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    document VARCHAR(14) NOT NULL,
    contactTel VARCHAR(15) NULL,
    contactCel VARCHAR(15) NOT NULL,
    email VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Address(
    id BIGINT(19) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    address VARCHAR(255) NOT NULL,
    personId BIGINT(19) NOT NULL,
    FOREIGN KEY (personId) REFERENCES Person(id)
);

CREATE TABLE IF NOT EXISTS Product(
    id BIGINT(19) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    personId BIGINT(19) NOT NULL,
    FOREIGN KEY (personId) REFERENCES Person(id)
);

CREATE TABLE IF NOT EXISTS RequestProd(
    id BIGINT(19) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    clientId BIGINT(19) NOT NULL,
    sellerId BIGINT(19) NOT NULL,
    FOREIGN KEY (clientId) REFERENCES Person(id),
    FOREIGN KEY (sellerId) REFERENCES Person(id)
);

CREATE TABLE IF NOT EXISTS Situation(
    id BIGINT(19) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    status VARCHAR(19) NOT NULL,
    requestProdId BIGINT(19) NOT NULL,
    FOREIGN KEY (requestProdId) REFERENCES RequestProd(id)
);

CREATE TABLE IF NOT EXISTS Parcel(
    id BIGINT(19) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    amount VARCHAR(19) NOT NULL,
    productId BIGINT(19) NOT NULL,
    requestProdId BIGINT(19) NOT NULL,
    FOREIGN KEY (ProductId) REFERENCES Product(id),
    FOREIGN KEY (requestProdId) REFERENCES RequestProd(id)
);