CREATE TABLE IF NOT EXISTS Person(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    document VARCHAR(14) NOT NULL,
    contactTel VARCHAR(15) NULL,
    contactCel VARCHAR(15) NOT NULL,
    email VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Address(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    address VARCHAR(255) NOT NULL,
    number INT NULL,
    city VARCHAR(255) NOT NULL,
    estate VARCHAR(255) NOT NULL,
    district VARCHAR(255) NOT NULL,
    zipCode VARCHAR(8) NOT NULL,
    personId BIGINT NOT NULL,
    FOREIGN KEY (personId) REFERENCES Person(id)
);

CREATE TABLE IF NOT EXISTS Product(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    price DOUBLE NOT NULL,
    personId BIGINT NOT NULL,
    FOREIGN KEY (personId) REFERENCES Person(id)
);

CREATE TABLE IF NOT EXISTS RequestProd(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    requestDate DATETIME NOT NULL,
    buyerId BIGINT NOT NULL,
    sellerId BIGINT NOT NULL,
    FOREIGN KEY (buyerId) REFERENCES Person(id),
    FOREIGN KEY (sellerId) REFERENCES Person(id)
);

CREATE TABLE IF NOT EXISTS Situation(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    status VARCHAR(19) NOT NULL,
    situationDate DATETIME NULL,
    requestProdId BIGINT NOT NULL,
    FOREIGN KEY (requestProdId) REFERENCES RequestProd(id)
);

CREATE TABLE IF NOT EXISTS Parcel(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    countProduct INT NOT NULL,
    price DOUBLE NOT NULL,
    productId BIGINT NOT NULL,
    requestProdId BIGINT NOT NULL,
    FOREIGN KEY (ProductId) REFERENCES Product(id),
    FOREIGN KEY (requestProdId) REFERENCES RequestProd(id)
);