CREATE TABLE IF NOT EXISTS Person(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    document VARCHAR(14) NOT NULL,
    contactCel VARCHAR(15) NOT NULL,
    contactTel VARCHAR(15) NULL,
    email VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Address(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    address VARCHAR(255) NOT NULL,
    number INT NULL,
    city VARCHAR(255) NOT NULL,
    state VARCHAR(255) NOT NULL,
    district VARCHAR(255) NOT NULL,
    zipCode VARCHAR(8) NOT NULL,
    personId BIGINT NOT NULL,
    FOREIGN KEY (personId) REFERENCES Person(id)
);

CREATE TABLE IF NOT EXISTS Product(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    price DOUBLE NOT NULL,
    personId BIGINT NOT NULL,
    FOREIGN KEY (personId) REFERENCES Person(id)
);

CREATE TABLE IF NOT EXISTS Request(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    requestDate DATETIME NOT NULL,
    buyerId BIGINT NOT NULL,
    sellerId BIGINT NOT NULL,
    FOREIGN KEY (buyerId) REFERENCES Person(id),
    FOREIGN KEY (sellerId) REFERENCES Person(id)
);

CREATE TABLE IF NOT EXISTS Situation(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    situationDate DATETIME NULL,
    statusId VARCHAR(19) NOT NULL,
    requestId BIGINT NOT NULL,
    FOREIGN KEY (requestId) REFERENCES Request(id),
    FOREIGN KEY (statusId) REFERENCES Status(id)
);

CREATE TABLE IF NOT EXISTS Parcel(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    countProduct INT NOT NULL,
    price DOUBLE NOT NULL,
    productId BIGINT NOT NULL,
    requestId BIGINT NOT NULL,
    FOREIGN KEY (productId) REFERENCES Product(id),
    FOREIGN KEY (requestId) REFERENCES Request(id)
);

CREATE TABLE IF NOT EXISTS Status(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    description VARCHAR(255) NOT NULL
);